# Generated by Django 5.0.4 on 2024-04-12 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_tag_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='articles.tag', verbose_name='<django.db.models.query_utils.DeferredAttribute object at 0x00000117904CE5D0>'),
        ),
    ]
